import type { DemoShape } from '../types';

// Representative names selected from the actual shape renderers.
// Geometry remains generated by the library, not by this catalog.
export const VARIANT_EXAMPLES: Partial<
  Record<DemoShape, { name: string; label: string }[]>
> = {
  planet: [
    {
      name: 'Variante 5',
      label: 'Con anillo · 0 lunas',
    },
    {
      name: 'Variante 2',
      label: 'Con anillo · 1 luna',
    },
    {
      name: 'Variante 7',
      label: 'Con anillo · 2 lunas',
    },
    {
      name: 'Variante 1',
      label: 'Sin anillo · 0 lunas',
    },
    {
      name: 'Variante 6',
      label: 'Sin anillo · 1 luna',
    },
    {
      name: 'Variante 10',
      label: 'Sin anillo · 2 lunas',
    },
  ],
  ghost: [
    {
      name: 'Variante 5',
      label: 'Ancho',
    },
    {
      name: 'Variante 1',
      label: 'Clásico',
    },
    {
      name: 'Variante 8',
      label: 'Cola lateral',
    },
    {
      name: 'Variante 3',
      label: 'Gotas',
    },
    {
      name: 'Variante 4',
      label: 'Sábana',
    },
  ],
  device: [
    {
      name: 'Variante 2',
      label: 'Celular',
    },
    {
      name: 'Variante 11',
      label: 'Escritorio',
    },
    {
      name: 'Variante 1',
      label: 'Notebook',
    },
    {
      name: 'Variante 6',
      label: 'Tablet',
    },
  ],
  flower: [
    {
      name: 'Variante 5',
      label: '5 pétalos',
    },
    {
      name: 'Variante 3',
      label: '6 pétalos',
    },
    {
      name: 'Variante 4',
      label: '7 pétalos',
    },
    {
      name: 'Variante 1',
      label: '8 pétalos',
    },
    {
      name: 'Variante 15',
      label: '9 pétalos',
    },
  ],
  robot: [
    {
      name: 'Variante 14',
      label: '0 antenas · con módulos · con tornillos',
    },
    {
      name: 'Variante 7',
      label: '0 antenas · con módulos · sin tornillos',
    },
    {
      name: 'Variante 5',
      label: '0 antenas · sin módulos · con tornillos',
    },
    {
      name: 'Variante 16',
      label: '0 antenas · sin módulos · sin tornillos',
    },
    {
      name: 'Variante 1',
      label: '1 antenas cuadradas · con módulos · con tornillos',
    },
    {
      name: 'Variante 4',
      label: '1 antenas cuadradas · con módulos · sin tornillos',
    },
    {
      name: 'Variante 17',
      label: '1 antenas cuadradas · sin módulos · con tornillos',
    },
    {
      name: 'Variante 21',
      label: '1 antenas cuadradas · sin módulos · sin tornillos',
    },
    {
      name: 'Variante 27',
      label: '1 antenas redondas · con módulos · con tornillos',
    },
    {
      name: 'Variante 20',
      label: '1 antenas redondas · con módulos · sin tornillos',
    },
    {
      name: 'Variante 29',
      label: '1 antenas redondas · sin módulos · con tornillos',
    },
    {
      name: 'Variante 6',
      label: '1 antenas redondas · sin módulos · sin tornillos',
    },
    {
      name: 'Variante 3',
      label: '2 antenas cuadradas · con módulos · con tornillos',
    },
    {
      name: 'Variante 9',
      label: '2 antenas cuadradas · con módulos · sin tornillos',
    },
    {
      name: 'Variante 43',
      label: '2 antenas cuadradas · sin módulos · con tornillos',
    },
    {
      name: 'Variante 36',
      label: '2 antenas cuadradas · sin módulos · sin tornillos',
    },
    {
      name: 'Variante 2',
      label: '2 antenas redondas · con módulos · con tornillos',
    },
    {
      name: 'Variante 10',
      label: '2 antenas redondas · con módulos · sin tornillos',
    },
    {
      name: 'Variante 69',
      label: '2 antenas redondas · sin módulos · con tornillos',
    },
    {
      name: 'Variante 22',
      label: '2 antenas redondas · sin módulos · sin tornillos',
    },
  ],
};
